### ISSUE TITLE
localhost:3000/api/chat 500 (Internal Server Error) 

### ISSUE THREAD

**Issue by lid3rs** [hillis/my-chat-app#8]
After launching the dev and attempt to submit the first query got:
localhost:3000/api/chat 500 (Internal Server Error) on client side and

```
error - Error: Request failed with status code 404
    at createError (/Users/x/Apps/gpt-4-chat-ui/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/x/Apps/gpt-4-chat-ui/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/x/Apps/gpt-4-chat-ui/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}
```
in console

**Comment by lid3rs** [comment]
can be closed, gpt-4 access was missing )
